name: studentscheduletracker
description: "A new Flutter project."

publish_to: 'none' 

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  firebase_core: ^3.5.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^8.0.2
  shimmer: ^3.0.0
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  dartz: ^0.10.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true

